quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.mcp.support-ops.transport-type=streamable-http
quarkus.langchain4j.mcp.support-ops.url=http://localhost:8081/mcp
quarkus.langchain4j.mcp.support-ops.log-requests=true
quarkus.langchain4j.mcp.support-ops.log-responses=true